name: "gif-explorer"

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
