name: "gif-explorer"

services:
  backedn-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=localhost:3000/api/gifs/
