FROM node:22.15.1-alpine AS builder
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM node:22.15.1-alpine 
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY --from=builder /app/dist /app/dist
RUN npm install pm2 -g
EXPOSE 3000
CMD [ "pm2-runtime", "/app/dist/index.js" ]